hm:
  db:
    host: 8.138.93.126 # 修改为你自己的虚拟机IP地址
    port: 3306
    database: db
    un: root
    pw: 34578234904 # 修改为docker中的MySQL密码
spring:
  cloud:
    sentinel:
      transport:
        dashboard: 8.138.93.126:8858
  redis:
    host: 8.138.93.126
    port: 6379
    database: 0

  nacos:
    server-addr: 8.210.154.174:8848
    ip: 8.210.154.174
    port: 8083