server:
  port: 8082
  tomcat:
    threads:
      max: 50 # 允许的最大线程数
    accept-count: 50 # 最大排队等待数量
    max-connections: 100 # 允许的最大连接
feign:
  okhttp:
    enabled: true # 开启OKHttp功能
  sentinel:
    enabled: true # 开启feign对sentinel的支持
hm:
  swagger:
    title: subject服务接口文档
    package: com.xhq.subject.controller

spring:
  application:
    name: subjectService
  profiles:
    active: dev
  cloud:
    sentinel:
      transport:
        dashboard: ${spring.cloud.sentinel.transport.dashboard}
      http-method-specify: true # 开启请求方式前缀
    nacos:
      server-addr: ${spring.nacos.server-addr} # nacos地址
  datasource:
    url: jdbc:mysql://${hm.db.host}:${hm.db.port}/db?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${hm.db.un}
    password: ${hm.db.pw}
  redis:
    host: ${spring.redis.host}
    port: ${spring.redis.port}
    database: 0


mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto

knife4j:
  enable: true
  openapi:
    title: subject管理接口文档
    description: "subject接口文档"
    email: qq.cn
    concat: q哥
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.xhq.subject.controller