hm:
  db:
    host: localhost # 修改为你自己的虚拟机IP地址
    port: 3306
    database: db
    un: root
    pw: 1234 # 修改为docker中的MySQL密码
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090
  redis:
    #    host: 8.218.203.188
    host: localhost
    port: 6379
    database: 0
  nacos:
    server-addr: 8.210.154.174:8848